import React from 'react';
import Nav from '../Nav';
import * as Styles from './Layout.style';
import Head from 'next/head';

const Layout: React.FC = ({ children }) => (
  <>
    <Head>
      <link
        rel="preload"
        href="/fonts/OpenSans/OpenSans-Light.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/OpenSans/OpenSans-LightItalic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/OpenSans/OpenSans-Regular.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/OpenSans/OpenSans-Italic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/OpenSans/OpenSans-SemiBold.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/OpenSans/OpenSans-Bold.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/OpenSans/OpenSans-BoldItalic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/OpenSans/OpenSans-ExtraBold.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/ProzaLibre/ProzaLibre-Regular.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/ProzaLibre/ProzaLibre-Italic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/ProzaLibre/ProzaLibre-Medium.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/ProzaLibre/ProzaLibre-MediumItalic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/ProzaLibre/ProzaLibre-SemiBold.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/ProzaLibre/ProzaLibre-SemiBoldItalic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/ProzaLibre/ProzaLibre-Bold.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/ProzaLibre/ProzaLibre-BoldItalic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/ProzaLibre/ProzaLibre-ExtraBold.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/ProzaLibre/ProzaLibre-ExtraBoldItalic.ttf"
        as="font"
        crossOrigin=""
      />
    </Head>
    <Styles.Main>
      <Nav />
      {children}
    </Styles.Main>
  </>
);
export default Layout;